pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd coit-backend1 && mvn install'
            }
        }
        stage('docker-build') {
            steps {
               sh 'cd coit-backend1 && docker build -t amol1996/coit-backend-12343243 .'
               sh 'docker images' 
            }
        }
        stage('docker-push') {
            steps {
               sh 'docker push amol1996/coit-backend-12343243'
            }
    }
}
}
