pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                cd coit-backend1 && mvn install
            }
        }
        stage('docker-build') {
            steps {
                cd coit-backend1
                docker build -t amol1996/coit-backend1-12344321:latest .
            }
        }
        stage('docker-push') {
            steps {
                docker push amol1996/coit-backend1-12344321:latest
            }
    }
}
}
